nss: fix compilation with glibc-2.24
`readdir_r` is deprecated as of glibc-2.24 and leads to a compilation
error:

| In file included from sysrand.c:16:0:
| unix_rand.c: In function 'ReadOneFile':
| unix_rand.c:1090:6: error: 'readdir_r' is deprecated [-Werror=deprecated-declarations]
|       error = readdir_r(fd, &entry_dir, &result);
|       ^~~~~
| In file included from unix_rand.c:1032:0,
|                  from sysrand.c:16:
| /usr/include/dirent.h:183:12: note: declared here
|  extern int readdir_r (DIR *__restrict __dirp,
|             ^~~~~~~~~
| cc1: all warnings being treated as errors

The issue is reported in nss bug tracker
(https://bugzilla.mozilla.org/show_bug.cgi?id=1254334) and fixed in nss
mainline.
The fixing patch is extracted from the nss source code repository.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>